version: '3.3'

services:
  photon:
    build: dockerfiles/minecraft-server/
    image: crae/minecraft-server
    volumes:
      - "./servers/photon/config:/config"
      - "./servers/photon/mods:/mods"
    environment:
      EULA: "TRUE"
      VERSION: "1.12.2"
      TYPE: "FORGE"
      FORGEVERSION: "14.23.5.2837"
      CONSOLE: "false"
      MEMORY: "4G"
      ONLINE_MODE: "FALSE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "ChangeMe"
      RCON_PORT: 28016
    env_file:
      - ./luckperm.env
    restart: unless-stopped

  lobby:
    image: crae/minecraft-server
    volumes:
      - "./servers/lobby/config:/config"
      - "./servers/lobby/mods:/mods"
    environment:
      EULA: "TRUE"
      VERSION: "1.12.2"
      TYPE: "SPONGEVANILLA"
      SPONGEVERSION: "1.12.2-7.1.5"
      CONSOLE: "false"
      MEMORY: "1G"
      ONLINE_MODE: "FALSE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "ChangeMe"
      RCON_PORT: 28016
    env_file:
      - ./luckperm.env
    restart: unless-stopped

  bungeecord:
    image: itzg/bungeecord
    ports:
      - 25577:25577
    volumes:
      - "./servers/bungeecord/config.yml:/server/config.yml"
      - "./servers/bungeecord/plugins:/plugins"
    restart: unless-stopped

  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    restart: unless-stopped
